createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupTeam"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .id + \"/home\""
            member: (.members | map(.user.username | tostring))
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupProject"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .__team_id + \"/v/b/li/\" + .id "
            startDate: if .start_date == null then "0000-00-00" else (.start_date | todate | tostring) end
            endDate: if .due_date == null then "0000-00-00" else (.due_date | todate | tostring) end
            totalIssues: .task_count
          relations:
            team: .__team_id
  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupIssue"'
          identifier: .id
          title: .name
          properties:
            description: .description
            url: .url
            status: .status.status
            assignee: if (.assignees | length) > 0 then .assignees[0].username else "" end
            creator: .creator.username | to
            priority: if .priority == null then "" else .priority
            created: if .date_created == null then "0000-00-00" else (.date_created | todate | tostring) end
            updated: if .date_updated == null then "0000-00-00" else (.date_updated | todate | tostring) end
          relations:
            project: .list.id
