createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupTeam"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .id + \"/home\""
            member: .members | map(.user.username)
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupProject"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .id + \"/list\""
            startDate: .start_date
            endDate: .end_date
            totalIssues: .task_count
  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupIssue"'
          identifier: .id | tostring
          title: .name
          properties:
            tags: .tags
            sloType: .type
            description: .description
            warningThreshold: .warning_threshold
            targetThreshold: .target_threshold
            createdBy: .creator.email
            createdAt: .created_at | todate
            updatedAt: .modified_at | todate
          relations:
            monitors: .monitor_ids | map(tostring)
            services: '.monitor_tags + .tags | map(select(startswith("service:"))) | unique | map(split(":")[1])'
