createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupTeam"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .id + \"/home\""
            members: '[.members[].user.email]'
  - kind: space
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupSpace"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .__team.id + \"/v/o/s/\" + .id"
            statuses: .statuses
            archived: .archived
            private: .private
          relations:
            team: .__team.id
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupProject"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .__team.id + \"/v/b/li/\" + .id"
            startDate: if .start_date!=null then .start_date | tonumber / 1000 | todate else "" | todate end
            endDate: if .due_date!=null then .due_date | tonumber / 1000 | todate else "" | todate end
            totalTasks: .task_count
          relations:
            space: .space.id
  - kind: task
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupTask"'
          identifier: .id
          title: .name
          properties:
            description: .description
            url: .url
            status: .status.status
            assignees: '[.assignees[].email]'
            creator: .creator.email | tostring
            priority: if .priority != null then .priority.priority else " " end
            created: if .date_created!=null then .date_created | tonumber / 1000 | todate else "" | todate end
            updated: if .date_updated!=null then .date_updated | tonumber / 1000 | todate else "" | todate end
          relations:
            project: .list.id
