createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupTeam"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .id + \"/home\""
            member: (.members | map(.user.username | tostring))
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupProject"'
          identifier: .id
          title: .name
          properties:
            url: "\"https://app.clickup.com/\" + .__team_id + \"/v/b/li/\" + .id "
            startDate: .start_date
            endDate: .due_date
            totalIssues: .task_count
          relations:
            team: .__team_id
  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"clickupIssue"'
          identifier: .id
          title: .name
          properties:
            description: .description
            url: .url
            status: .status.status
            assignee: (.assignees | map(.username | tostring) | first)
            creator: .creator.username | to
            priority: .priority
            created: if .date_created == null then null else .date_created | todate end
            updated: if .date_updated == null then null else .date_updated | todate end
          relations:
            project: .list.id
